// Date: 01/07/2013 19:22:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.Electrolysm.electro.basic.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPetriDish extends ModelBase
{
  //fields
    ModelRenderer Corner;
    ModelRenderer Corner2;
    ModelRenderer Corner3;
    ModelRenderer Corner4;
    ModelRenderer Corner5;
    ModelRenderer Corner6;
    ModelRenderer Corner8;
    ModelRenderer Shape9;
    ModelRenderer Centre1;
    ModelRenderer Centre2;
    ModelRenderer Centre3;
  
  public ModelPetriDish()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Corner = new ModelRenderer(this, 0, 0);
      Corner.addBox(0F, 0F, 0F, 3, 1, 1);
      Corner.setRotationPoint(-3F, 23F, -1F);
      Corner.setTextureSize(64, 64);
      Corner.mirror = true;
      setRotation(Corner, 0F, 0.7853982F, 0F);
      Corner2 = new ModelRenderer(this, 0, 0);
      Corner2.addBox(0F, 0F, 0F, 3, 1, 1);
      Corner2.setRotationPoint(2F, 23F, -2F);
      Corner2.setTextureSize(64, 64);
      Corner2.mirror = true;
      setRotation(Corner2, 0F, 3.141593F, 0F);
      Corner3 = new ModelRenderer(this, 0, 0);
      Corner3.addBox(0F, 0F, 0F, 3, 1, 1);
      Corner3.setRotationPoint(2F, 23F, 3F);
      Corner3.setTextureSize(64, 64);
      Corner3.mirror = true;
      setRotation(Corner3, 0F, 3.141593F, 0F);
      Corner4 = new ModelRenderer(this, 0, 0);
      Corner4.addBox(0F, 0F, 0F, 3, 1, 1);
      Corner4.setRotationPoint(-2.3F, 23F, 0.1F);
      Corner4.setTextureSize(64, 64);
      Corner4.mirror = true;
      setRotation(Corner4, 0F, -0.8225768F, 0F);
      Corner5 = new ModelRenderer(this, 0, 0);
      Corner5.addBox(0F, 0F, 0F, 1, 1, 2);
      Corner5.setRotationPoint(-3F, 23F, -1F);
      Corner5.setTextureSize(64, 64);
      Corner5.mirror = true;
      setRotation(Corner5, 0F, 0F, 0F);
      Corner6 = new ModelRenderer(this, 0, 0);
      Corner6.addBox(0F, 0F, 0F, 3, 1, 1);
      Corner6.setRotationPoint(1.4F, 23F, 2.3F);
      Corner6.setTextureSize(64, 64);
      Corner6.mirror = true;
      setRotation(Corner6, 0F, 0.7853982F, 0F);
      Corner8 = new ModelRenderer(this, 0, 0);
      Corner8.addBox(0F, 0F, 0F, 3, 1, 1);
      Corner8.setRotationPoint(2F, 23F, -3F);
      Corner8.setTextureSize(64, 64);
      Corner8.mirror = true;
      setRotation(Corner8, 0F, -0.7110409F, 0F);
      Shape9 = new ModelRenderer(this, 0, 0);
      Shape9.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape9.setRotationPoint(3.3F, 23F, -1F);
      Shape9.setTextureSize(64, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Centre1 = new ModelRenderer(this, 0, 0);
      Centre1.addBox(0F, 0F, 0F, 4, 1, 4);
      Centre1.setRotationPoint(-1F, 23F, -2F);
      Centre1.setTextureSize(64, 64);
      Centre1.mirror = true;
      setRotation(Centre1, 0F, 0F, 0F);
      Centre2 = new ModelRenderer(this, 0, 0);
      Centre2.addBox(0F, 0F, 0F, 1, 1, 3);
      Centre2.setRotationPoint(-2F, 23F, -1.6F);
      Centre2.setTextureSize(64, 64);
      Centre2.mirror = true;
      setRotation(Centre2, 0F, 0F, 0F);
      Centre3 = new ModelRenderer(this, 0, 0);
      Centre3.addBox(0F, 0F, 0F, 1, 1, 2);
      Centre3.setRotationPoint(3F, 23F, -1F);
      Centre3.setTextureSize(64, 64);
      Centre3.mirror = true;
      setRotation(Centre3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Corner.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
    Corner5.render(f5);
    Corner6.render(f5);
    Corner8.render(f5);
    Shape9.render(f5);
    Centre1.render(f5);
    Centre2.render(f5);
    Centre3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
